# -*- coding: utf-8 -*-
"""Breast_Cancer_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2zrKvddDIJcvLhcJuFbUWFyXsSWw2OB

### Final Year IBM Project (2025-26)

##### Project Title:

> Breast Cancer Detection in Healthcare

##### Project Description:

> Our project aims to predict breast cancer using machine learning techniques in Python. The model is built using the **Breast Cancer Wisconsin (Diagnostic) Dataset** from `sklearn.datasets`, which contains various medical attributes related to cell nuclei features.

##### Submitted by:
> 1. Aditya Gupta (202210101150125)
2. Akshat Yadav (202210101150121)

---

> **Importing The Dependencies**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.datasets
from sklearn.model_selection import train_test_split

"""> **Data Collection & Processing**"""

# Laoding The Dataset: We have used the in-built dataset from sklearn.datasets
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

print(breast_cancer_dataset)

# Loading The Data To a Data Frame
data_frame = pd.DataFrame(breast_cancer_dataset.data, columns = breast_cancer_dataset.feature_names)

# Print The First 5 Rows Of The Data Frame
data_frame.head()

# Adding The 'target' Column To The Data Frame
data_frame['label'] = breast_cancer_dataset.target

# Print The Last 5 Rows Of The Data Frame
data_frame.tail()

# Number Of Columns And Rows In The Dataset
data_frame.shape

# Getting Some Information About The Data
data_frame.info()

# Checking For Missing Values
data_frame.isnull().sum()

# Statistical Measures About The Data
data_frame.describe()

#Checking The Distribution Of Target Value
data_frame['label'].value_counts()

"""> 1 → Benign <br>
0 → Malignant
"""

data_frame.groupby('label').mean()

"""> **Separating the features and target**"""

X = data_frame.drop(columns='label', axis=1)
Y = data_frame['label']

print(X)

print(Y)

"""> **Splitting the data into training data & Testing data**"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

"""> **Standardize the data**"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

"""> **Building the Neural Network**

"""

# Importing Tensorflow and Keras
import tensorflow as tf
tf.random.set_seed(3)
from tensorflow import keras

# Setting up the layers of Neural Network

model = keras.Sequential([
                          keras.layers.Flatten(input_shape=(30,)),
                          keras.layers.Dense(20, activation='relu'),
                          keras.layers.Dense(2, activation='sigmoid')
])

# Compiling the Neural Network

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Training the Neural Network

history = model.fit(X_train_std, Y_train, validation_split=0.1, epochs=10)

"""> **Visualizing accuracy and loss**"""

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')

plt.legend(['training data', 'validation data'], loc = 'lower right')

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')

plt.legend(['training data', 'validation data'], loc = 'upper right')

"""> **Accuracy of the model on test data**"""

loss, accuracy = model.evaluate(X_test_std, Y_test)
print(accuracy)

print(X_test_std.shape)
print(X_test_std[0])

Y_pred = model.predict(X_test_std)

print(Y_pred.shape)
print(Y_pred[0])

print(X_test_std)

print(Y_pred)

"""> **`Model.predict()` gives the prediction probability of each class for that data point**"""

# Argmax function

my_list = [0.25, 0.56]

index_of_max_value = np.argmax(my_list)
print(my_list)
print(index_of_max_value)

# Converting the prediction probability to class labels

Y_pred_labels = [np.argmax(i) for i in Y_pred]
print(Y_pred_labels)

"""> **Building the predictive system**"""

input_data = (11.76,21.6,74.72,427.9,0.08637,0.04966,0.01657,0.01115,0.1495,0.05888,0.4062,1.21,2.635,28.47,0.005857,0.009758,0.01168,0.007445,0.02406,0.001769,12.98,25.72,82.98,516.5,0.1085,0.08615,0.05523,0.03715,0.2433,0.06563)

# Change the input_data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# Reshape the numpy array as we are predicting for one data point
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# Standardizing the input data
input_data_std = scaler.transform(input_data_reshaped)

prediction = model.predict(input_data_std)
print(prediction)

prediction_label = [np.argmax(prediction)]
print(prediction_label)

if(prediction_label[0] == 0):
  print('The tumor is Malignant')

else:
  print('The tumor is Benign')